- name: Example playbook
  hosts:
    - localhost
  vars_files:
    - vars/test-case-full.yaml
  tasks:
    - name: Use module from collection source
      khmarochos.pki.init_dictionary:
        pki_ca_cascade: "{{ pki_ca_cascade }}"
      register: result
    - name: Show the calculations' result
      debug:
        msg: "{{ result.result }}"
    - name: Use module from collection source
      khmarochos.pki.init_pki:
        pki_ca_cascade: "{{ pki_ca_cascade }}"
    - debug:
        msg: "I hope, you're satisfied with the result ;-)"
