- name: Example playbook

  hosts:
    - localhost

  vars_files:
    - vars/test-case-full.yaml

  tasks:

    - name: Initialise the configuration dictionary
      khmarochos.pki.init_dictionary:
        pki_ca_cascade: "{{ pki_cascade_configuration }}"
      register: configuration_dictionary

    - name: Retrieve the calculations' result
      set_fact:
        configuration_dictionary: "{{ configuration_dictionary.result }}"

    - name: Show the calculations' result
      debug:
        msg: "{{ configuration_dictionary }}"

#    - name: Look up something
#      debug:
#        msg: "{{ lookup('khmarochos.pki.pki_dictionary', ca='root', parameter='certificate_chain_file') }}"

    - name: Initialise the PKI cascade
      khmarochos.pki.init_pki:
        pki_ca_cascade: "{{ pki_cascade_configuration }}"
        save_forced: true

    - name: Issue a certificate
      khmarochos.pki.issue_everything:
        pki_ca_cascade: "{{ pki_cascade_configuration }}"
        ca_nickname: root
        certificate_parameters:
          nickname: test-server
          certificate_type: server
          certificate_term: 365
          private_key_passphrase_random: true
          private_key_encrypted: true
      register: certificate

    - name: Show the certificate's information
      debug:
        msg: "{{ certificate.result }}"

    - name: Issue a certificate
      khmarochos.pki.issue_everything:
        pki_ca_cascade: "{{ pki_cascade_configuration }}"
        ca_nickname: root
        certificate_parameters:
          nickname: test-client
          certificate_type: client
          certificate_term: 365
          certificate_subject_alternative_names:
            - DNS:localhost
            - IP:127.0.0.1
          private_key_passphrase_random: true
          private_key_encrypted: true
      register: certificate

    - name: Show the certificate's information
      debug:
        msg: "{{ certificate.result }}"

    - name: Issue a server's certificate
      khmarochos.pki.issue_everything:
        pki_ca_cascade: "{{ pki_cascade_configuration }}"
        ca_nickname: root
        certificate_parameters:
          nickname: test-server
          certificate_type: server
          certificate_term: 365
          private_key_passphrase_random: true
          private_key_encrypted: true
      register: certificate

    - name: Show the server's certificate's information
      debug:
        msg: "{{ certificate.result }}"

    - name: Issue a client's certificate
      khmarochos.pki.issue_everything:
        pki_ca_cascade: "{{ pki_cascade_configuration }}"
        ca_nickname: root
        certificate_parameters:
          nickname: test-client
          certificate_type: client
          certificate_term: 365
          private_key_passphrase_random: true
          private_key_encrypted: true
      register: certificate

    - name: Show the client's certificate's information
      debug:
        msg: "{{ certificate.result }}"

    - name: Issue a server's/client's certificate
      khmarochos.pki.issue_everything:
        pki_ca_cascade: "{{ pki_cascade_configuration }}"
        ca_nickname: root
        certificate_parameters:
          nickname: test-server-client
          certificate_type: server-client
          certificate_term: 365
          private_key_passphrase_random: true
          private_key_encrypted: true
      register: certificate

    - name: Show the server's/client's certificate's information
      debug:
        msg: "{{ certificate.result }}"

    - name: Issue a certificate
      khmarochos.pki.issue_everything:
        pki_ca_cascade: "{{ pki_cascade_configuration }}"
        ca_nickname: root
        certificate_parameters:
          nickname: test-none
          certificate_type: none
          certificate_term: 365
          private_key_passphrase_random: true
          private_key_encrypted: true
      register: certificate

    - name: Show the certificate's information
      debug:
        msg: "{{ certificate.result }}"